version: 1
builder:
  configs:
  - platform: watchos
    scheme: SpotifyAPI
  - platform: ios
    scheme: SpotifyAPI
  - platform: macos
    scheme: SpotifyAPI
  - platform: tvos
    scheme: SpotifyAPI
  - platform: linux
    scheme: SpotifyAPI
